namespace Core.Security
{
    public enum PermissionType
    {
        ViewEmployees,
        ViewDepartments,
        ViewEstablishments,
        ViewUserAccounts,
        ViewAllEmployees,
        ViewAllDepartments,
        ViewAllEstablishments,
        ViewAllUserAccounts,
        AddDepartment,
        AddEmployee,
        AddUserAccount,
        AddFunction,
        AddTimeInterval,
        EditDepartment,
        EditUserAccount,
        EditEstablishment,
        EditEmployee,
        EditFunction,
        EditTimeInterval,
        RemoveDepartment,
        RemoveUserAccount,
        RemoveEstablishment,
        RemoveEmployee,
        RemoveFunction,
        RemoveTimeInterval
    }
}
